# Ingress resource for the application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-recommendation
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: movie-recommendation.local
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 31798
